service: ${self:custom.serviceName}
app: data-service

plugins:
  - serverless-s3-local
  - serverless-offline
  - serverless-python-requirements
  - serverless-plugin-lambda-insights

frameworkVersion: '2'

custom:
  serviceName: image-optimization
  stage: ${opt:stage, self:custom.defaultStage}
  defaultStage: dev
  imagesBucket: labelity-use-${self:custom.stage}-images
  envFile: ${file(env.${opt:stage, self:provider.stage}.json)}
  pythonRequirements:
    dockerizePip: true
    useStaticCache: false
    useDownloadCache: false
  stages:
    - ${opt:stage}
    - dev
    - integration
    - production

provider:
  name: aws
  runtime: python3.7
  lambdaHashingVersion: 20201221
  region: us-east-1

  usagePlan:
    quota:
      limit: 100
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 100
      rateLimit: 50

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: arn:aws:s3:::${self:custom.imagesBucket}/*
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: arn:aws:s3:::${self:custom.imagesBucket}/raw/*
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: arn:aws:s3:::${self:custom.imagesBucket}/thumbnails/*
    - Effect: "Allow"
      Action:
        - "s3:DeleteObject"
        - "s3:GetObject"
      Resource: arn:aws:s3:::${self:custom.imagesBucket}/videos/*

package:
  individually: true

functions:
  optimize:
    handler: handler.main
    module: image_processor
    memorySize: 256
    lambdaInsights: true
    package: { }
    environment: ${self:custom.envFile}
    events:
      - s3:
          bucket: ${self:custom.imagesBucket}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: raw/

  update_images:
    handler: handler.main
    module: image_processor
    memorySize: 256
    lambdaInsights: true
    package: { }
    environment: ${self:custom.envFile}
    events:
      - s3:
          bucket: ${self:custom.imagesBucket}
          event: s3:ObjectRemoved:*
          existing: true
          rules:
            - prefix: raw/

  video_to_frames:
    handler: handler.main
    module: video_processor
    lambdaInsights: true
    memorySize: 512
    environment: ${self:custom.envFile}
    events:
      - s3:
          bucket: ${self:custom.imagesBucket}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: videos/
